### ISSUE TITLE
Module Not working 

### ISSUE THREAD

**Issue by SadifRayhan** [NawabHost/bkash-checkout-for-whmcs#14]
![Screenshot_20220922-151913](https://user-images.githubusercontent.com/36522543/191758495-24d29a9e-cea9-47d3-a581-861368e07014.png)
The module does not work after activation displays an error when the payment button is clicked.

Php version 7.2
SSL activated and working properly.

**Comment by AminulBD** [comment]
Hi,

Thank you for trying our module on your platform. But a few things needs to be clear before you started using this module.

1. You have valid productions checkout credentials for your merchant account from bKash. legacy or USSD based keys will not work in order to use this checkout module.
2. You must have valid url set on your whmcs setup section.
3. SSL is required.
4. we tested our module with php 7.4, use other version at your own risk.
5. This module is free and OSS so there is no warranty or guarantee that this module work on your platform.
6. Self-Service module.

If you have legacy api keys then you will need this: https://github.com/NawabHost/bkash-merchant-for-whmcs


If you have still issue, please see other issue (open + closed) in this repo to resolve your issue.

**Comment by SadifRayhan** [comment]
I am testing using sandbox credential. It is not working with this
